#端口 访问位置
server:
  port: 9002
  servlet:
    context-path: /

#spring应用名称
spring:
  application:
    name: offcnpe_provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.33.170:3306/offcnpe?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: "0000"
    type: com.alibaba.druid.pool.DruidDataSource

#mybatis-plus
mybatis-plus:
  configuration:
    #开启驼峰标识
    map-underscore-to-camel-case: true
    #控制台显示sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    #逻辑删除
    db-config:
      logic-not-delete-value: 1
      logic-delete-value: 0
  #加载xml文件
  mapper-locations: classpath:/mappers/xml/*.xml
  type-aliases-package: com.offcn.pojo

#dubbo端口和名称
dubbo:
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://10.10.33.170:2181
    timeout: 10000
  scan:
    base-packages: com.offcn.service.impl