server:
  port: 9005
  servlet:
    context-path: /

spring:
  application:
    name: offcnpe_job
  redis:
    host: 10.10.33.170
    port: 6379
    password: 123456

excelFilePath: E:/code/uploadfile/offcnpe/excel/
imgFilePath: E:/code/uploadfile/offcnpe/img/