server:
  port: 9003
  servlet:
    context-path: /

#spring应用名称
spring:
  application:
    name: offcnpe_customer
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  redis:
    host: 10.10.33.170
    port: 6379
    password: 123456

dubbo:
  scan:
    base-packages: com.offcn.controller
  registry:
    address: zookeeper://10.10.33.170:2181
    timeout: 100000

excelFilePath: E:/code/uploadfile/offcnpe/excel/
imgFilePath: E:/code/uploadfile/offcnpe/img/